### PR TITLE
Add table_flipper to Ruby section

### PR DESCRIPTION
**Pull request by iridakos**
## What does this project do?

Adds the table flip to Ruby exceptions.

## Why is that entertaining?

(╯°□°）╯︵ ┻━┻

## How hard did you laugh? Was it just a silent giggle or was it full blown laughing and howling and screaming "OH MY GOD! EVERYONE! OH MY GOD! THIS IS THE FUNNIEST THING EVER! YOU'VE GOT TO SEE THIS!!!"

Rails error

### CODE REVIEW

**Comment by mislavcimpersak** [comment]
EVERY exception handler should implement this!!


Could you just please change the name of the project to `Table Flipper` or `Exception Table Flipper`?

**Comment by iridakos** [comment]
Of course! Done (╯°□°）╯︵ ┻━┻

**Comment by mislavcimpersak** [comment]
Thanks mate. Everything is better with a table flipper 😅

**Comment by iridakos** [comment]
Thanks!

**Pull request merged**
