### PR TITLE
Clarify the role of esoteric programming languages

### PR DESCRIPTION
**Pull request by JesseTG**
Esoteric languages are a popular enough idea to warrant their own list.  I propose that this list touch upon the idea, but ultimately link to [this](https://github.com/sindresorhus/awesome/pull/934) or similar when it's ready.  Also, I added Brainfuck because you're not allowed to say "esolang" without mentioning it in the same sentence.

## What does this project do?

No project (unless you count me adding Brainfuck to the list); this clarifies the scope of the list.

## Why is that entertaining?

Esolangs are great
So great, they would drown this list
It's for your safety

## How hard did you laugh? Was it just a silent giggle or was it full blown laughing and howling and screaming "OH MY GOD! EVERYONE! OH MY GOD! THIS IS THE FUNNIEST THING EVER! YOU'VE GOT TO SEE THIS!!!"

Not all that relevant here.  I giggled a bit with that haiku, I guess.

### CODE REVIEW

**Comment by mislavcimpersak** [comment]
I'm not sure if a section description is really needed.

First reason being that all the other sections are already without descriptions so to keep it consistent _Languages_ section should also be without one. Second reason because I really hope that people realise not to use this in production since it is after all _a fun_ list 😃 

Perhaps just change the name of the section to `Esotheric languages` but without the description? That should be enough for people to get the basic idea what these languages are 😁

**Comment by mislavcimpersak** [comment]
@JesseTG could you please comment on my suggestion? 🤠

**Comment by JesseTG** [comment]
Crap, didn't notice the ping, sorry.

The description itself isn't important; moreso is leaving the bulk of information about esolangs to a dedicated list, since the subculture around them is vast and capable of drowning out this one.

**Comment by JesseTG** [comment]
Imagine a hypothetical `awesome-ubuntu` list.  There are many Linux resources out there, and the vast majority of them are relevant for Ubuntu.  But would you really need to list them all?  Why not stuff them in a dedicated `awesome-linux` list?

**Comment by nickserv** [comment]
I'm in favor of the separate esolangs list because it has so much of its own content (and useful subsections). However, maybe it would be best to remove the description until that list is ready, and just add Brainfuck here for now (since it's a classic esolang and deserves mention).

**Comment by mislavcimpersak** [comment]
@JesseTG I agree that we are not trying to collect esoteric languages here. There already is an awesome list of [esoteric langauges](https://github.com/angrykoala/awesome-esoteric).
 We just sometimes pop a few in that are funny and somewhat current 😄

**Comment by JesseTG** [comment]
> @JesseTG I agree that we are not trying to collect esoteric languages here.

Okay, glad we're on the same page.

> There already is an awesome list of esoteric langauges.

Yep, I just didn't want to be specific until it was finalized.  I imagine by the time we finish this conversation that list will be ready, anyway.

> We just sometimes pop a few in that are funny and somewhat current :smile:

I can get behind that if it's limited to absolute star players.  I wouldn't consider the three currently listed as such, though.

One other possible reason for keeping esolangs out of this list; esolangs actually have some value, in that they can be instructive in teaching concepts of programming languages, automata theory, virtual machines, and computability.  A brainfuck interpreter would be a great exercise for an introductory CS course, for example.

**Pull request closed without merging**
